from enum import StrEnum


class Intent(StrEnum):
    GENERAL_QA = "GENERAL_QA"
    DATA_ANALYSIS_QA = "DATA_ANALYSIS_QA"
    DATA_ANALYSIS_EXECUTION = "DATA_ANALYSIS_EXECUTION"
    CODE_EXECUTION = "CODE_EXECUTION"


class ExecutionMode(StrEnum):
    SINGLE = "SINGLE"
    MULTI = "MULTI"


class PlanningKind(StrEnum):
    FIXED_WORKFLOW = "FIXED_WORKFLOW"
    TOOL_PLAN = "TOOL_PLAN"
    CUSTOM_CODE = "CUSTOM_CODE"


class RiskLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class TaskStatus(StrEnum):
    ACCEPTED = "ACCEPTED"
    CLASSIFYING = "CLASSIFYING"
    ANSWERING = "ANSWERING"
    PLANNING = "PLANNING"
    WAITING_FOR_APPROVAL = "WAITING_FOR_APPROVAL"
    REVISING_PLAN = "REVISING_PLAN"
    QUEUED_FOR_EXECUTION = "QUEUED_FOR_EXECUTION"
    EXECUTING = "EXECUTING"
    WAITING_FOR_EXECUTOR_EVENT = "WAITING_FOR_EXECUTOR_EVENT"
    FINALIZING_EXECUTION = "FINALIZING_EXECUTION"
    GENERATING_REPORT = "GENERATING_REPORT"
    SUCCEEDED = "SUCCEEDED"
    REJECTED = "REJECTED"
    FAILED = "FAILED"
    CANCEL_REQUESTED = "CANCEL_REQUESTED"
    CANCELLED = "CANCELLED"

    @property
    def is_terminal(self) -> bool:
        return self in {
            self.SUCCEEDED,
            self.REJECTED,
            self.FAILED,
            self.CANCELLED,
        }


class PlanDecisionType(StrEnum):
    APPROVE = "APPROVE"
    REVISE = "REVISE"
    REJECT = "REJECT"


class ResumeSignalType(StrEnum):
    CLARIFICATION = "CLARIFICATION"
    WORKFLOW_SELECTION = "WORKFLOW_SELECTION"
    EXECUTION_MODE = "EXECUTION_MODE"
    REQUEST_RISK_CONFIRMATION = "REQUEST_RISK_CONFIRMATION"
    PLAN_REVIEW = "PLAN_REVIEW"
    EXECUTOR_BOUNDARY = "EXECUTOR_BOUNDARY"
    CANCEL_REQUESTED = "CANCEL_REQUESTED"


class ExecutorOutcome(StrEnum):
    WAITING = "WAITING"
    OPERATION_SUCCEEDED = "OPERATION_SUCCEEDED"
    OPERATION_FAILED = "OPERATION_FAILED"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class MultiAction(StrEnum):
    APPEND_STEP = "APPEND_STEP"
    REQUIRE_REAPPROVAL = "REQUIRE_REAPPROVAL"
    FINALIZE = "FINALIZE"
    FAIL = "FAIL"
