"""Shared business topology during the session-graph migration."""

from langgraph.graph import END, START

from ex_agent.graph.routes import (
    route_approved_execution,
    route_code_risk,
    route_external_signal,
    route_intent,
    route_multi_action,
    route_plan_review,
    route_reconciliation,
    route_request_risk,
    route_workflow_decision,
    route_workflow_search,
)

NODES = (
    "hydrate_turn",
    "classify_intent",
    "clarify_request",
    "answer_general",
    "answer_data_question",
    "commit_answer",
    "choose_execution_mode",
    "review_request_risk",
    "confirm_request_risk",
    "search_workflows",
    "choose_workflow",
    "load_selected_workflow",
    "build_plan",
    "compile_and_persist_plan",
    "review_compiled_code_risk",
    "review_plan",
    "verify_approval",
    "submit_execution",
    "wait_external_signal",
    "reconcile_executor",
    "adapt_multi_plan",
    "append_operation",
    "finalize_execution",
    "cancel_execution",
    "build_report_evidence",
    "generate_report",
    "commit_success",
    "commit_rejected",
    "commit_blocked",
    "commit_failed",
    "commit_cancelled",
)

EDGES = (
    (START, "hydrate_turn"),
    ("hydrate_turn", "classify_intent"),
    ("clarify_request", "classify_intent"),
    ("answer_general", "commit_answer"),
    ("answer_data_question", "commit_answer"),
    ("commit_answer", END),
    ("choose_execution_mode", "review_request_risk"),
    ("build_plan", "compile_and_persist_plan"),
    ("compile_and_persist_plan", "review_compiled_code_risk"),
    ("load_selected_workflow", "review_compiled_code_risk"),
    ("submit_execution", "wait_external_signal"),
    ("append_operation", "wait_external_signal"),
    ("finalize_execution", "wait_external_signal"),
    ("cancel_execution", "wait_external_signal"),
    ("build_report_evidence", "generate_report"),
    ("generate_report", "commit_success"),
    ("commit_success", END),
    ("commit_rejected", END),
    ("commit_blocked", END),
    ("commit_failed", END),
    ("commit_cancelled", END),
)

ROUTES = {
    "classify_intent": route_intent,
    "review_request_risk": route_request_risk,
    "confirm_request_risk": route_request_risk,
    "search_workflows": route_workflow_search,
    "choose_workflow": route_workflow_decision,
    "review_compiled_code_risk": route_code_risk,
    "review_plan": route_plan_review,
    "verify_approval": route_approved_execution,
    "wait_external_signal": route_external_signal,
    "reconcile_executor": route_reconciliation,
    "adapt_multi_plan": route_multi_action,
}
